dbConfig:
  dsn: "root:root@tcp(127.0.0.1:3306)/shop?charset=utf8mb4&parseTime=True&loc=Local"
  maxOpenConn: 20
  maxLifeTime: 1800
  maxIdleConn: 5

server:
  rpc_port: 8080
  http_port: 8090

apis:
  - name: userlist
    table: users
    sql: "select * from users where id > @id"
  - name: add_user
    table: users
    sql: "insert into users(username,password,mobile) values (@username, @password, @mobile)"
    select:
      sql: "SELECT LAST_INSERT_ID() as user_id"